import DualTree

/-!
Transitive axiom audit for the first source-facing validation facts.
-/

#print axioms DualTree.isPrefix_refl
#print axioms DualTree.isPrefix_trans
#print axioms DualTree.OrderAudit.canonical_order_counterexample
#print axioms DualTree.Insensitivity.constantOn_union_of_overlap
#print axioms DualTree.SpanAudit.singleton_span_subset
#print axioms DualTree.BinarySkewAudit.remark2_witness_is_semicomplete_printed
#print axioms DualTree.BinarySkewAudit.remark2_interior_not_skew_printed
#print axioms DualTree.Remark1Audit.forwardS_is_skew
#print axioms DualTree.Remark1Audit.forwardTprime_is_skew
#print axioms DualTree.Remark1Audit.no_forward_complete_extension

#print axioms DualTree.SpanAudit.eval_substitute
#print axioms DualTree.SpanAudit.span_substitute_subset
#print axioms DualTree.SpanAudit.symbol_eq_of_all_evals
#print axioms DualTree.SpanAudit.constant_preserved_of_span_subset
#print axioms DualTree.SpanAudit.fibre_uniform_of_span_subset
#print axioms DualTree.SpanAudit.span_subset_iff_substitution
#print axioms DualTree.SkewTree.singleton_skewB
#print axioms DualTree.SkewTree.singleton_complete_oneB

#print axioms DualTree.isPrefix_antisymm
#print axioms DualTree.VariableWord.every_var_occurs
#print axioms DualTree.VariableWord.span_subset_iff_substitution
#print axioms DualTree.VariableWord.support_subset_of_span_subset

#print axioms DualTree.StarInsensitivity.starRelated_iff
#print axioms DualTree.StarInsensitivity.singleton_insensitive
#print axioms DualTree.StarInsensitivity.disjoint_union_failure
#print axioms DualTree.StarInsensitivity.starInsensitive_union_of_overlap

#print axioms DualTree.Theorem3Audit.root_support_complete
#print axioms DualTree.Theorem3Audit.left_support_complete
#print axioms DualTree.Theorem3Audit.supports_differ
#print axioms DualTree.Theorem3Audit.unary_spans_equal
#print axioms DualTree.Theorem3Audit.two_colors_below_every_candidate

#print axioms DualTree.UnaryMainAudit.unary_refines_all
#print axioms DualTree.UnaryMainAudit.rootWord_complete
#print axioms DualTree.UnaryMainAudit.leftWord_complete
#print axioms DualTree.UnaryMainAudit.no_homogeneous_one
#print axioms DualTree.UnaryMainAudit.no_unary_eventual_bound

#print axioms DualTree.Corollary22Audit.color_is_smooth
#print axioms DualTree.Corollary22Audit.no_monochromatic_complete_candidate
#print axioms DualTree.Corollary22Audit.canonical_complete_one
#print axioms DualTree.Corollary22Audit.canonical_good_for_every_coloring

#print axioms DualTree.VariableWord.supportNodes_nodup
#print axioms DualTree.KVariableWord.refines_refl
#print axioms DualTree.KVariableWord.refines_trans
#print axioms DualTree.KVariableWord.refines_iff_syntactic
#print axioms DualTree.KVariableWord.support_subset_of_refines

#print axioms DualTree.KVariableWord.substitute_compose
#print axioms DualTree.KVariableWord.syntacticRefines_refl
#print axioms DualTree.KVariableWord.syntacticRefines_trans
#print axioms DualTree.KVariableWord.syntacticRefines_refines
#print axioms DualTree.KVariableWord.support_subset_of_syntacticRefines

#print axioms DualTree.VectorSkew.binaryHeightOneVector_complete
#print axioms DualTree.VectorSkew.binaryHeightOneVectorReversed_not_complete

#print axioms DualTree.MixedProduct.VariableWord.word_mem_of_mem_span
#print axioms DualTree.MixedProduct.VariableWord.upPoint_mem_of_mem_span
#print axioms DualTree.MixedProduct.VariableWord.bulletPoint_mem_support_of_mem_span

#print axioms DualTree.MixedProduct.good_iff_same_bulletRecord
#print axioms DualTree.MixedProduct.color_eq_of_good_of_same_record

#print axioms DualTree.GluingAudit.short_tail_stays_in_hom_tree
#print axioms DualTree.GluingAudit.exact_tail_leaves_hom_tree

#print axioms DualTree.MixedProduct.VariableWord.refines_refl
#print axioms DualTree.MixedProduct.VariableWord.refines_trans
#print axioms DualTree.MixedProduct.VariableWord.refines_of_syntactic_components
#print axioms DualTree.MixedProduct.good_of_refines
#print axioms DualTree.MixedProduct.good_of_syntactic_refinement

#print axioms DualTree.MixedProduct.noBulletIndex_elim
#print axioms DualTree.MixedProduct.good_iff_constant_on_span_of_noBullet
#print axioms DualTree.MixedProduct.good_of_constant_on_span_of_noBullet

#print axioms DualTree.MixedProduct.sameUpTrace_refl
#print axioms DualTree.MixedProduct.upCanonical_of_refines
#print axioms DualTree.MixedProduct.upCanonical_of_good_of_noBullet
#print axioms DualTree.MixedProduct.upCanonical_of_constant_on_span

#print axioms DualTree.MixedProduct.sameUpTrace_iff_record_eq
#print axioms DualTree.MixedProduct.upCanonical_iff_same_record
#print axioms DualTree.MixedProduct.color_eq_of_upCanonical_of_same_record

#print axioms DualTree.MixedProduct.prefix_values_eq_of_root_values_eq
#print axioms DualTree.MixedProduct.sameUpTrace_iff_supportTraceRecord_eq_of_mem_span
#print axioms DualTree.MixedProduct.upCanonical_iff_same_supportTraceRecord

#print axioms DualTree.Lemma27Audit.printed_projection_address_overflows
#print axioms DualTree.Lemma27Audit.safe_cone_tail
#print axioms DualTree.Lemma27Audit.two_symbols_cannot_cover_three_variables
#print axioms DualTree.Lemma27Audit.occurrence_based_freezing_not_substitution

#print axioms DualTree.Lemma27Repair.restrictSupportWord_substitution
#print axioms DualTree.Lemma27Repair.restrictSupport_span_subset
#print axioms DualTree.Lemma27Repair.restrictSupport_support

#print axioms DualTree.PartialColoring.exists_equivalence_respecting_extension
#print axioms DualTree.PartialColoring.partial_coloring_compatible_of_extension

#print axioms DualTree.MixedProduct.smoothRelated_refl
#print axioms DualTree.MixedProduct.smoothRelated_symm
#print axioms DualTree.MixedProduct.smoothRelated_trans
#print axioms DualTree.MixedProduct.exists_smooth_extension

#print axioms DualTree.Lemma27Repair.visibleAncestors_length_le_height
#print axioms DualTree.Lemma27Repair.auxiliary_symbols_cover_indices
#print axioms DualTree.Lemma27Repair.visibleAncestors_auxiliary_coverage

#print axioms DualTree.CutPreservation.prefix_eq_of_length_eq
#print axioms DualTree.CutPreservation.lengthTie_of_prefix
#print axioms DualTree.CutPreservation.paperAux_of_prefix
#print axioms DualTree.CutPreservation.forwardAux_of_prefix
#print axioms DualTree.CutPreservation.underlyingSymbol_eq_of_syntactic_cut
#print axioms DualTree.CutPreservation.paperCut_preserved_of_syntactic_refinement
#print axioms DualTree.CutPreservation.forwardCut_preserved_of_syntactic_refinement
#print axioms DualTree.CutPreservation.paperCut_preserved_of_span_refinement
#print axioms DualTree.CutPreservation.forwardCut_preserved_of_span_refinement

#print axioms DualTree.CutFrontier.take_length_of_prefix
#print axioms DualTree.CutFrontier.prefix_of_prefix_length_le
#print axioms DualTree.CutFrontier.frontier_antichain
#print axioms DualTree.CutFrontier.exists_frontier_above
#print axioms DualTree.CutFrontier.frontier_unique_above
#print axioms DualTree.CutFrontier.exists_unique_frontier_above
#print axioms DualTree.CutFrontier.paperCut_exists_unique_frontier
#print axioms DualTree.CutFrontier.forwardCut_exists_unique_frontier

#print axioms DualTree.SignatureBoundary.beforeCut_of_proper_prefix
#print axioms DualTree.SignatureBoundary.boundary_at_cut
#print axioms DualTree.SignatureBoundary.prefix_mem_ambientPath
#print axioms DualTree.SignatureBoundary.mem_ambientPath_prefix
#print axioms DualTree.SignatureBoundary.boundary_iff_frontier
#print axioms DualTree.SignatureBoundary.existsUnique_boundary_on_path
#print axioms DualTree.SignatureBoundary.firstBoundary_spec

#print axioms DualTree.StarredSignature.variable_root_in_interior
#print axioms DualTree.StarredSignature.variable_at_interior
#print axioms DualTree.StarredSignature.exceptionalLeaves_spec
#print axioms DualTree.StarredSignature.interior_mem_signatureTree
#print axioms DualTree.StarredSignature.prefixWord_eq_of_syntactic_refinement

#print axioms DualTree.StarredSignature.allFin_length
#print axioms DualTree.StarredSignature.allFin_nonempty
#print axioms DualTree.StarredSignature.filter_conj_eq_nil
#print axioms DualTree.StarredSignature.leaf_not_before_of_fullBefore
#print axioms DualTree.StarredSignature.immediateSuccs_nil_of_not_interior
#print axioms DualTree.StarredSignature.exceptionalLeaves_not_before_of_fullBefore
#print axioms DualTree.StarredSignature.interior_mem_signatureTree_of_fullBefore

#print axioms DualTree.StarredSignature.singleton_interior_nil
#print axioms DualTree.StarredSignature.fullBefore_at_maxInterior
#print axioms DualTree.StarredSignature.exceptionalLeaves_not_before_of_maxInterior
#print axioms DualTree.StarredSignature.interior_mem_signatureTree_at_maxInterior

#print axioms DualTree.SignatureFrontier.boundary_prefix_frontier_of_shared_descendant
#print axioms DualTree.SignatureFrontier.boundary_prefix_unique_frontier_of_support_extension

#print axioms DualTree.ConeFrontier.beforeCut_of_prefix
#print axioms DualTree.ConeFrontier.outside_of_prefix
#print axioms DualTree.ConeFrontier.unique_frontier_in_outside_cone
#print axioms DualTree.ConeFrontier.unique_frontier_of_signature_boundary

#print axioms DualTree.MeetGeometry.commonPrefix_prefix_left
#print axioms DualTree.MeetGeometry.commonPrefix_comm
#print axioms DualTree.MeetGeometry.commonPrefix_prefix_right
#print axioms DualTree.MeetGeometry.commonPrefix_append_left
#print axioms DualTree.MeetGeometry.prefix_commonPrefix
#print axioms DualTree.MeetGeometry.coneMeetClosed_of_meetClosed
#print axioms DualTree.MeetGeometry.meetClosed_of_coneMeetClosed
#print axioms DualTree.MeetGeometry.coneMeetClosed_iff_meetClosed
#print axioms DualTree.MeetGeometry.unique_frontier_of_boundary_of_meetClosed

#print axioms DualTree.SignatureMarker.boundaryMarker_has_leaf
#print axioms DualTree.SignatureMarker.boundaryMarker_has_support_descendant
#print axioms DualTree.SignatureMarker.coneMarker_has_support_descendant

#print axioms DualTree.DirectionalSupport.mem_allFin
#print axioms DualTree.DirectionalSupport.prefix_of_isPrefixOf_true
#print axioms DualTree.DirectionalSupport.descendant_of_uniqueBranch
#print axioms DualTree.DirectionalSupport.directional_descendants_of_fullBefore
#print axioms DualTree.DirectionalSupport.coneMarker_has_descendant_of_fullBefore

#print axioms DualTree.SkewLevelOrder.condIIIB_of_skew
#print axioms DualTree.SkewLevelOrder.length_lt_of_height_lt
#print axioms DualTree.SkewLevelOrder.paperAux_of_height_lt
#print axioms DualTree.SkewLevelOrder.forwardAux_of_height_lt
#print axioms DualTree.SkewLevelOrder.coneMarker_has_descendant_of_height_lt

#print axioms DualTree.SkewBranchGeometry.isPrefixOf_true_of_prefix
#print axioms DualTree.SkewBranchGeometry.strictPrefixB_iff
#print axioms DualTree.SkewBranchGeometry.immediateSuccB_iff
#print axioms DualTree.SkewBranchGeometry.mem_branchWitnesses_iff
#print axioms DualTree.SkewBranchGeometry.exists_first_immediate_on_path
#print axioms DualTree.SkewBranchGeometry.eq_of_mem_uniqueBranch

#print axioms DualTree.MeetClosedFromBranching.length_lt_of_strictPrefix
#print axioms DualTree.MeetClosedFromBranching.exists_longer_common_support_prefix
#print axioms DualTree.MeetClosedFromBranching.commonPrefix_mem_of_support_root
#print axioms DualTree.MeetClosedFromBranching.meetClosed_of_rooted_uniqueDirections

#print axioms DualTree.CompleteSkewMeet.full_directions_at_complete_witness
#print axioms DualTree.CompleteSkewMeet.branchWitnesses_nil_of_immediateSuccs_nil
#print axioms DualTree.CompleteSkewMeet.condIVB_of_skew_nonSingleton
#print axioms DualTree.CompleteSkewMeet.rootedB_of_skew_nonSingleton
#print axioms DualTree.CompleteSkewMeet.atMostOneDirection_of_complete_total
#print axioms DualTree.CompleteSkewMeet.meetClosed_of_complete_total

#print axioms DualTree.finLexLE_total
#print axioms DualTree.SkewMeetInstantiation.paperAux_total
#print axioms DualTree.SkewMeetInstantiation.forwardAux_total
#print axioms DualTree.SkewMeetInstantiation.paperAuxB_total
#print axioms DualTree.SkewMeetInstantiation.forwardAuxB_total
#print axioms DualTree.SkewMeetInstantiation.meetClosed_singleton
#print axioms DualTree.SkewMeetInstantiation.meetClosed_length_one
#print axioms DualTree.SkewMeetInstantiation.meetClosed_complete_paper
#print axioms DualTree.SkewMeetInstantiation.meetClosed_complete_forward
#print axioms DualTree.SkewMeetInstantiation.unique_frontier_complete_paper
#print axioms DualTree.SkewMeetInstantiation.unique_frontier_complete_forward

#print axioms DualTree.InclusiveFrontier.outside_of_prefix
#print axioms DualTree.InclusiveFrontier.unique_frontier_of_boundary
#print axioms DualTree.InclusiveFrontier.unique_frontier_complete_paper
#print axioms DualTree.InclusiveSignatureMarkers.child_paperCutBoundary
#print axioms DualTree.InclusiveSignatureMarkers.boundaryMarker_paperCutBoundary
#print axioms DualTree.InclusiveSignatureMarkers.coneMarker_paperCutBoundary
#print axioms DualTree.InclusiveSignatureMarkers.boundaryMarker_unique_frontier
#print axioms DualTree.InclusiveSignatureMarkers.coneMarker_unique_frontier_of_height_lt

#print axioms DualTree.CompleteInteriorBranching.nonleaf_of_height_lt
#print axioms DualTree.CompleteInteriorBranching.fullDirections_of_complete_nonleaf_total
#print axioms DualTree.CompleteInteriorBranching.fullDirections_of_height_lt_paper
#print axioms DualTree.CompleteInteriorBranching.coneMarker_descendant_of_height_lt
#print axioms DualTree.CompleteInteriorBranching.coneMarker_unique_frontier_of_complete_height

#print axioms DualTree.MarkerAntichain.eq_of_prefix_boundaries
#print axioms DualTree.MarkerAntichain.unique_candidate_marker_in_cone
#print axioms DualTree.LiteralSignatureR.mem_signatureTree_iff
#print axioms DualTree.LiteralSignatureR.literalR_subset_coneMarkers
#print axioms DualTree.LiteralSignatureR.literalR_unique_marker_in_cone
#print axioms DualTree.LiteralSignatureR.literalR_unique_inclusive_frontier

#print axioms DualTree.SignatureInteriorPersistence.interior_of_strict_descendant
#print axioms DualTree.SignatureInteriorPersistence.interiorPersists_of_maxInterior
#print axioms DualTree.SignatureInteriorPersistence.interiorPersists_at_maxInterior
#print axioms DualTree.SignatureInteriorPersistence.literalR_unique_frontier_of_maxInterior

#print axioms DualTree.LiteralFrontierCleanup.nonsingleton_of_early_level
#print axioms DualTree.LiteralFrontierCleanup.coneMarker_unique_frontier
#print axioms DualTree.LiteralFrontierCleanup.literalR_unique_frontier
#print axioms DualTree.LiteralFrontierCleanup.child_bounded_of_support_descendant
#print axioms DualTree.LiteralFrontierCleanup.all_children_bounded_of_early_level

#print axioms DualTree.LiteralFrontierIndex.frontierFor_spec
#print axioms DualTree.LiteralFrontierIndex.frontierFor_eq_of_frontier
#print axioms DualTree.LiteralFrontierIndex.frontierFor_injective

#print axioms DualTree.ConeLocalDecoder.visibleAncestor_spec
#print axioms DualTree.ConeLocalDecoder.visibleAncestor_get_prefix
#print axioms DualTree.ConeLocalDecoder.indexMap_surjective
#print axioms DualTree.ConeLocalDecoder.decode_empty
#print axioms DualTree.ConeLocalDecoder.decode_onto_visible
#print axioms DualTree.ConeLocalDecoder.decodeRoot_prefix

#print axioms DualTree.SupportHeightRanks.heightAt_lt_of_strictPrefix
#print axioms DualTree.SupportHeightRanks.heightAt_injective_on_common_path

#print axioms DualTree.RankCardinality.nodup_length_le_of_rank_bound

#print axioms DualTree.FrontierHeightBound.frontier_height_le_cut_succ
#print axioms DualTree.FrontierHeightBound.frontier_height_le_complete
#print axioms DualTree.FrontierHeightBound.frontier_height_le_m_succ
#print axioms DualTree.FrontierHeightBound.decodeAtFrontier_onto_visible

#print axioms DualTree.Lemma27Repair.substituteRoots_span_subset
#print axioms DualTree.Lemma27Repair.substituteRoots_support
#print axioms DualTree.Lemma27Repair.substituteRoots_fibre_uniform

#print axioms DualTree.Lemma27Repair.reconstructComplete_supportNodes
#print axioms DualTree.Lemma27Repair.reconstructComplete_syntacticRefines
#print axioms DualTree.Lemma27Repair.reconstructComplete_refines
#print axioms DualTree.Lemma27Repair.reconstructComplete_prefixWord_eq

#print axioms DualTree.ConeWordLift.liftWord_original
#print axioms DualTree.ConeWordLift.liftWord_auxiliary
#print axioms DualTree.ConeWordLift.liftWord_variable
#print axioms DualTree.ConeWordLift.liftWord_variable_fibre
#print axioms DualTree.ConeWordLift.eval_liftWord
#print axioms DualTree.ConeWordLift.liftAtCone_aux_prefix
#print axioms DualTree.ConeWordLift.liftAtCone_variable

#print axioms DualTree.ConeProjectionAlgebra.prefix_append_left
#print axioms DualTree.ConeProjectionAlgebra.projection_prefix
#print axioms DualTree.ConeProjectionAlgebra.projection_cone
#print axioms DualTree.ConeProjectionAlgebra.projection_nil
#print axioms DualTree.ConeProjectionAlgebra.projection_rooted_at_frontier
#print axioms DualTree.ConeProjectionAlgebra.projection_leftInverse_root

#print axioms DualTree.ConeRootAlignment.lifted_variable_root_prefix
#print axioms DualTree.ConeRootAlignment.root_alignment_of_code
#print axioms DualTree.ConeProjectionAlignment.lifted_root_prefix
#print axioms DualTree.ConeProjectionAlignment.source_root_alignment

#print axioms DualTree.LiteralFrontierCount.mem_frontiers_iff
#print axioms DualTree.LiteralFrontierCount.frontiers_nodup
#print axioms DualTree.LiteralFrontierCount.literalR_nodup
#print axioms DualTree.LiteralFrontierCount.literalR_length_le_frontiers
#print axioms DualTree.LiteralFrontierCount.frontier_partition_count
#print axioms DualTree.ConeTailDomains.variable_cone_tail_safe
#print axioms DualTree.ConeTailDomains.common_cone_tail_safe
#print axioms DualTree.ConeTailDomains.variable_frontier_tail_safe

#print axioms DualTree.CanonicalSupportWalk.next_prefix
#print axioms DualTree.CanonicalSupportWalk.next_unique
#print axioms DualTree.CanonicalSupportWalk.next_mem
#print axioms DualTree.CanonicalSupportWalk.walk_append
#print axioms DualTree.CanonicalSupportWalk.walk_root_prefix
#print axioms DualTree.CanonicalSupportWalk.walk_prefix
#print axioms DualTree.CanonicalSupportWalk.walk_first_direction
#print axioms DualTree.CanonicalSupportWalk.walk_mem_of_admissible
#print axioms DualTree.CanonicalSupportWalk.projection_walk_prefix

#print axioms DualTree.CompleteSupportRoot.exists_root
#print axioms DualTree.CompleteSupportRoot.rootOf_mem
#print axioms DualTree.CompleteSupportRoot.rootOf_prefix
#print axioms DualTree.CompleteSupportRoot.canonicalWalk_nil
#print axioms DualTree.CompleteSupportRoot.canonicalWalk_prefix
#print axioms DualTree.CompleteSupportRoot.canonicalWalk_mem_of_admissible
#print axioms DualTree.CompleteSupportRoot.canonicalProjection_prefix

#print axioms DualTree.ImmediateSupportHeight.mem_preds_iff
#print axioms DualTree.ImmediateSupportHeight.mem_preds_immediate_iff
#print axioms DualTree.ImmediateSupportHeight.heightAt_immediate
#print axioms DualTree.ImmediateSupportHeight.heightAt_root_zero
#print axioms DualTree.ImmediateSupportHeight.heightAt_next

#print axioms DualTree.CompleteSupportAddresses.support_nodup
#print axioms DualTree.CompleteSupportAddresses.branch_of_height_lt
#print axioms DualTree.CompleteSupportAddresses.admissible_and_height
#print axioms DualTree.CompleteSupportAddresses.canonical_bounded_address
#print axioms DualTree.CompleteSupportAddresses.canonicalEmbedding_height
#print axioms DualTree.CompleteSupportAddresses.canonicalEmbedding_prefix

#print axioms DualTree.CanonicalSupportInjective.walk_injective_of_admissible
#print axioms DualTree.CanonicalSupportInjective.canonicalEmbedding_injective

#print axioms DualTree.SupportReachability.nonsingleton_of_distinct_members
#print axioms DualTree.SupportReachability.first_direction_of_strictPrefix
#print axioms DualTree.SupportReachability.unique_direction_of_immediate
#print axioms DualTree.SupportReachability.next_eq_of_immediate
#print axioms DualTree.SupportReachability.walk_address_of_prefix
#print axioms DualTree.SupportReachability.walk_height_of_admissible
#print axioms DualTree.SupportReachability.support_has_address

#print axioms DualTree.CompleteSupportSurjective.heightAt_le_length
#print axioms DualTree.CompleteSupportSurjective.exists_terminal_above
#print axioms DualTree.CompleteSupportSurjective.heightAt_lt_k
#print axioms DualTree.CompleteSupportSurjective.canonicalEmbedding_surjective
#print axioms DualTree.CompleteSupportSurjective.canonicalEmbedding_bijective
#print axioms DualTree.CompleteSupportSurjective.inverse_right
#print axioms DualTree.CompleteSupportSurjective.inverse_left
#print axioms DualTree.CompleteSupportSurjective.inverse_length

#print axioms DualTree.CanonicalSupportPrefixIso.heightAt_le_of_prefix
#print axioms DualTree.CanonicalSupportPrefixIso.canonicalEmbedding_prefix_reflect
#print axioms DualTree.CanonicalSupportPrefixIso.canonicalEmbedding_prefix_iff
#print axioms DualTree.CanonicalSupportPrefixIso.inverseAddress_prefix

#print axioms DualTree.CanonicalConeCoordinates.address_empty
#print axioms DualTree.CanonicalConeCoordinates.project_empty
#print axioms DualTree.CanonicalConeCoordinates.project_prefix
#print axioms DualTree.CanonicalConeCoordinates.project_cone
#print axioms DualTree.CanonicalConeCoordinates.project_height
#print axioms DualTree.CanonicalConeCoordinates.inverse_project
#print axioms DualTree.CanonicalConeCoordinates.inverse_project_tail

#print axioms DualTree.FrontierAntichainPadding.prefix_pad
#print axioms DualTree.FrontierAntichainPadding.pad_length
#print axioms DualTree.FrontierAntichainPadding.comparable_of_pad_eq
#print axioms DualTree.FrontierAntichainPadding.eq_of_pad_eq_antichain
#print axioms DualTree.FrontierAntichainPadding.pad_injective_on_antichain

#print axioms DualTree.FrontierSourcePadding.inverse_frontier_rank_bound
#print axioms DualTree.FrontierSourcePadding.inverse_frontier_antichain
#print axioms DualTree.FrontierSourcePadding.padded_frontier_length
#print axioms DualTree.FrontierSourcePadding.padded_frontier_injective

#print axioms DualTree.FrontierCardinality.paddedSource_injective_frontiers
#print axioms DualTree.FrontierCardinality.paddedSource_frontier_length
#print axioms DualTree.FrontierCardinality.frontiers_length_le_pow

#print axioms DualTree.LiteralMarkerCoordinates.frontierMember_injective
#print axioms DualTree.LiteralMarkerCoordinates.coordinate_frontier
#print axioms DualTree.LiteralMarkerCoordinates.coordinate_injective

#print axioms DualTree.CanonicalConeWordTransport.totalProjection_empty
#print axioms DualTree.CanonicalConeWordTransport.totalProjection_prefix
#print axioms DualTree.CanonicalConeWordTransport.totalProjection_cone
#print axioms DualTree.CanonicalConeWordTransport.totalProjection_eq_project
#print axioms DualTree.CanonicalConeWordTransport.lifted_root_prefix
#print axioms DualTree.CanonicalConeWordTransport.source_root_alignment

#print axioms DualTree.MixedProduct.bulletKindOfRange_iff
#print axioms DualTree.MixedProduct.bulletKindOfRange_ne_up
#print axioms DualTree.MixedProduct.bulletIndex_injective
#print axioms DualTree.MixedProduct.bulletIndex_surjective
#print axioms DualTree.MixedProduct.bulletIndex_bijective
#print axioms DualTree.LiteralMarkerProductKind.literalMarker_bullet_bijective

#print axioms DualTree.MixedProduct.bulletIndex_markerOfBullet
#print axioms DualTree.MixedProduct.markerOfBullet_bulletIndex
#print axioms DualTree.MixedProduct.elementFromMarkers_words
#print axioms DualTree.MixedProduct.elementFromMarkers_bullet
#print axioms DualTree.LiteralMarkerMixedElement.assemble_marker_point

#print axioms DualTree.UniformConeDomains.commonTail_value
#print axioms DualTree.UniformConeDomains.projectCommon_prefix
#print axioms DualTree.UniformConeDomains.projectCommon_cone
#print axioms DualTree.UniformConeDomains.projectCommon_height
#print axioms DualTree.UniformConeDomains.projectCommon_inverse
#print axioms DualTree.UniformConeDomains.extraLevelTail_value
#print axioms DualTree.UniformConeDomains.projectExtraLevel_prefix
#print axioms DualTree.UniformConeDomains.projectExtraLevel_inverse

#print axioms DualTree.MixedProduct.conePatch_outside
#print axioms DualTree.MixedProduct.conePatch_inside
#print axioms DualTree.MixedProduct.patchedWords_plain
#print axioms DualTree.MixedProduct.patchedWords_bullet_outside
#print axioms DualTree.MixedProduct.patchedWords_bullet_inside
#print axioms DualTree.MixedProduct.patchedElement_smooth
#print axioms DualTree.MixedProduct.smoothColor_invariant_under_patches
#print axioms DualTree.BulletSmoothnessAudit.related_despite_different_marked_letters
#print axioms DualTree.BulletSmoothnessAudit.markedLetterColor_not_smooth

#print axioms DualTree.InverseConeTails.relativeTail_length
#print axioms DualTree.InverseConeTails.relativeTail_address
#print axioms DualTree.InverseConeTails.inverseAddress_injective
#print axioms DualTree.InverseConeTails.projectCommon_reaches_target
#print axioms DualTree.InverseConeTails.projectCommon_injective

#print axioms DualTree.Lemma27SignatureTree.frontierAt_spec
#print axioms DualTree.Lemma27SignatureTree.markedProjection_frontier_prefix
#print axioms DualTree.Lemma27SignatureTree.markedProjection_injective
#print axioms DualTree.Lemma27SignatureTree.signatureNodes_base
#print axioms DualTree.Lemma27SignatureTree.signatureNodes_marked
#print axioms DualTree.Lemma27SignatureTree.signatureNodes_eq_of_gamma2_smooth
#print axioms DualTree.Lemma27SignatureTree.sourceSignatureNodes_eq_of_gamma2_smooth

#print axioms DualTree.Lemma27ConeIndex.projectSlot_cone
#print axioms DualTree.Lemma27ConeIndex.projectSlot_injective
#print axioms DualTree.Lemma27ConeIndex.locateSlot_spec
#print axioms DualTree.Lemma27ConeIndex.locateSlot_projectSlot
#print axioms DualTree.Lemma27ConeIndex.locateSlot_none_iff
