import DualTree

/-!
Transitive axiom audit for the first source-facing validation facts.
-/

#print axioms DualTree.isPrefix_refl
#print axioms DualTree.isPrefix_trans
#print axioms DualTree.OrderAudit.canonical_order_counterexample
#print axioms DualTree.Insensitivity.constantOn_union_of_overlap
#print axioms DualTree.SpanAudit.singleton_span_subset
#print axioms DualTree.BinarySkewAudit.remark2_witness_is_semicomplete_printed
#print axioms DualTree.BinarySkewAudit.remark2_interior_not_skew_printed
#print axioms DualTree.Remark1Audit.forwardS_is_skew
#print axioms DualTree.Remark1Audit.forwardTprime_is_skew
#print axioms DualTree.Remark1Audit.no_forward_complete_extension

#print axioms DualTree.SpanAudit.eval_substitute
#print axioms DualTree.SpanAudit.span_substitute_subset
#print axioms DualTree.SpanAudit.symbol_eq_of_all_evals
#print axioms DualTree.SpanAudit.constant_preserved_of_span_subset
#print axioms DualTree.SpanAudit.fibre_uniform_of_span_subset
#print axioms DualTree.SpanAudit.span_subset_iff_substitution
#print axioms DualTree.SkewTree.singleton_skewB
#print axioms DualTree.SkewTree.singleton_complete_oneB

#print axioms DualTree.isPrefix_antisymm
#print axioms DualTree.VariableWord.every_var_occurs
#print axioms DualTree.VariableWord.span_subset_iff_substitution
#print axioms DualTree.VariableWord.support_subset_of_span_subset

#print axioms DualTree.StarInsensitivity.starRelated_iff
#print axioms DualTree.StarInsensitivity.singleton_insensitive
#print axioms DualTree.StarInsensitivity.disjoint_union_failure
#print axioms DualTree.StarInsensitivity.starInsensitive_union_of_overlap

#print axioms DualTree.Theorem3Audit.root_support_complete
#print axioms DualTree.Theorem3Audit.left_support_complete
#print axioms DualTree.Theorem3Audit.supports_differ
#print axioms DualTree.Theorem3Audit.unary_spans_equal
#print axioms DualTree.Theorem3Audit.two_colors_below_every_candidate

#print axioms DualTree.UnaryMainAudit.unary_refines_all
#print axioms DualTree.UnaryMainAudit.rootWord_complete
#print axioms DualTree.UnaryMainAudit.leftWord_complete
#print axioms DualTree.UnaryMainAudit.no_homogeneous_one
#print axioms DualTree.UnaryMainAudit.no_unary_eventual_bound

#print axioms DualTree.Corollary22Audit.color_is_smooth
#print axioms DualTree.Corollary22Audit.no_monochromatic_complete_candidate
#print axioms DualTree.Corollary22Audit.canonical_complete_one
#print axioms DualTree.Corollary22Audit.canonical_good_for_every_coloring

#print axioms DualTree.VariableWord.supportNodes_nodup
#print axioms DualTree.KVariableWord.refines_refl
#print axioms DualTree.KVariableWord.refines_trans
#print axioms DualTree.KVariableWord.refines_iff_syntactic
#print axioms DualTree.KVariableWord.support_subset_of_refines

#print axioms DualTree.KVariableWord.substitute_compose
#print axioms DualTree.KVariableWord.syntacticRefines_refl
#print axioms DualTree.KVariableWord.syntacticRefines_trans
#print axioms DualTree.KVariableWord.syntacticRefines_refines
#print axioms DualTree.KVariableWord.support_subset_of_syntacticRefines

#print axioms DualTree.VectorSkew.binaryHeightOneVector_complete
#print axioms DualTree.VectorSkew.binaryHeightOneVectorReversed_not_complete

#print axioms DualTree.MixedProduct.VariableWord.word_mem_of_mem_span
#print axioms DualTree.MixedProduct.VariableWord.upPoint_mem_of_mem_span
#print axioms DualTree.MixedProduct.VariableWord.bulletPoint_mem_support_of_mem_span

#print axioms DualTree.MixedProduct.good_iff_same_bulletRecord
#print axioms DualTree.MixedProduct.color_eq_of_good_of_same_record

#print axioms DualTree.GluingAudit.short_tail_stays_in_hom_tree
#print axioms DualTree.GluingAudit.exact_tail_leaves_hom_tree

#print axioms DualTree.MixedProduct.VariableWord.refines_refl
#print axioms DualTree.MixedProduct.VariableWord.refines_trans
#print axioms DualTree.MixedProduct.VariableWord.refines_of_syntactic_components
#print axioms DualTree.MixedProduct.good_of_refines
#print axioms DualTree.MixedProduct.good_of_syntactic_refinement

#print axioms DualTree.MixedProduct.noBulletIndex_elim
#print axioms DualTree.MixedProduct.good_iff_constant_on_span_of_noBullet
#print axioms DualTree.MixedProduct.good_of_constant_on_span_of_noBullet

#print axioms DualTree.MixedProduct.sameUpTrace_refl
#print axioms DualTree.MixedProduct.upCanonical_of_refines
#print axioms DualTree.MixedProduct.upCanonical_of_good_of_noBullet
#print axioms DualTree.MixedProduct.upCanonical_of_constant_on_span

#print axioms DualTree.MixedProduct.sameUpTrace_iff_record_eq
#print axioms DualTree.MixedProduct.upCanonical_iff_same_record
#print axioms DualTree.MixedProduct.color_eq_of_upCanonical_of_same_record

#print axioms DualTree.MixedProduct.prefix_values_eq_of_root_values_eq
#print axioms DualTree.MixedProduct.sameUpTrace_iff_supportTraceRecord_eq_of_mem_span
#print axioms DualTree.MixedProduct.upCanonical_iff_same_supportTraceRecord

#print axioms DualTree.Lemma27Audit.printed_projection_address_overflows
#print axioms DualTree.Lemma27Audit.safe_cone_tail
#print axioms DualTree.Lemma27Audit.two_symbols_cannot_cover_three_variables
#print axioms DualTree.Lemma27Audit.occurrence_based_freezing_not_substitution

#print axioms DualTree.Lemma27Repair.restrictSupportWord_substitution
#print axioms DualTree.Lemma27Repair.restrictSupport_span_subset
#print axioms DualTree.Lemma27Repair.restrictSupport_support

#print axioms DualTree.PartialColoring.exists_equivalence_respecting_extension
#print axioms DualTree.PartialColoring.partial_coloring_compatible_of_extension

#print axioms DualTree.MixedProduct.smoothRelated_refl
#print axioms DualTree.MixedProduct.smoothRelated_symm
#print axioms DualTree.MixedProduct.smoothRelated_trans
#print axioms DualTree.MixedProduct.exists_smooth_extension

#print axioms DualTree.Lemma27Repair.visibleAncestors_length_le_height
#print axioms DualTree.Lemma27Repair.auxiliary_symbols_cover_indices
#print axioms DualTree.Lemma27Repair.visibleAncestors_auxiliary_coverage

#print axioms DualTree.CutPreservation.prefix_eq_of_length_eq
#print axioms DualTree.CutPreservation.lengthTie_of_prefix
#print axioms DualTree.CutPreservation.paperAux_of_prefix
#print axioms DualTree.CutPreservation.forwardAux_of_prefix
#print axioms DualTree.CutPreservation.underlyingSymbol_eq_of_syntactic_cut
#print axioms DualTree.CutPreservation.paperCut_preserved_of_syntactic_refinement
#print axioms DualTree.CutPreservation.forwardCut_preserved_of_syntactic_refinement
#print axioms DualTree.CutPreservation.paperCut_preserved_of_span_refinement
#print axioms DualTree.CutPreservation.forwardCut_preserved_of_span_refinement

#print axioms DualTree.CutFrontier.take_length_of_prefix
#print axioms DualTree.CutFrontier.prefix_of_prefix_length_le
#print axioms DualTree.CutFrontier.frontier_antichain
#print axioms DualTree.CutFrontier.exists_frontier_above
#print axioms DualTree.CutFrontier.frontier_unique_above
#print axioms DualTree.CutFrontier.exists_unique_frontier_above
#print axioms DualTree.CutFrontier.paperCut_exists_unique_frontier
#print axioms DualTree.CutFrontier.forwardCut_exists_unique_frontier

#print axioms DualTree.SignatureBoundary.beforeCut_of_proper_prefix
#print axioms DualTree.SignatureBoundary.boundary_at_cut
#print axioms DualTree.SignatureBoundary.prefix_mem_ambientPath
#print axioms DualTree.SignatureBoundary.mem_ambientPath_prefix
#print axioms DualTree.SignatureBoundary.boundary_iff_frontier
#print axioms DualTree.SignatureBoundary.existsUnique_boundary_on_path
#print axioms DualTree.SignatureBoundary.firstBoundary_spec

#print axioms DualTree.StarredSignature.variable_root_in_interior
#print axioms DualTree.StarredSignature.variable_at_interior
#print axioms DualTree.StarredSignature.exceptionalLeaves_spec
#print axioms DualTree.StarredSignature.interior_mem_signatureTree
#print axioms DualTree.StarredSignature.prefixWord_eq_of_syntactic_refinement

#print axioms DualTree.StarredSignature.allFin_length
#print axioms DualTree.StarredSignature.allFin_nonempty
#print axioms DualTree.StarredSignature.filter_conj_eq_nil
#print axioms DualTree.StarredSignature.leaf_not_before_of_fullBefore
#print axioms DualTree.StarredSignature.immediateSuccs_nil_of_not_interior
#print axioms DualTree.StarredSignature.exceptionalLeaves_not_before_of_fullBefore
#print axioms DualTree.StarredSignature.interior_mem_signatureTree_of_fullBefore

#print axioms DualTree.StarredSignature.singleton_interior_nil
#print axioms DualTree.StarredSignature.fullBefore_at_maxInterior
#print axioms DualTree.StarredSignature.exceptionalLeaves_not_before_of_maxInterior
#print axioms DualTree.StarredSignature.interior_mem_signatureTree_at_maxInterior

#print axioms DualTree.SignatureFrontier.boundary_prefix_frontier_of_shared_descendant
#print axioms DualTree.SignatureFrontier.boundary_prefix_unique_frontier_of_support_extension

#print axioms DualTree.ConeFrontier.beforeCut_of_prefix
#print axioms DualTree.ConeFrontier.outside_of_prefix
#print axioms DualTree.ConeFrontier.unique_frontier_in_outside_cone
#print axioms DualTree.ConeFrontier.unique_frontier_of_signature_boundary

#print axioms DualTree.MeetGeometry.commonPrefix_prefix_left
#print axioms DualTree.MeetGeometry.commonPrefix_comm
#print axioms DualTree.MeetGeometry.commonPrefix_prefix_right
#print axioms DualTree.MeetGeometry.commonPrefix_append_left
#print axioms DualTree.MeetGeometry.prefix_commonPrefix
#print axioms DualTree.MeetGeometry.coneMeetClosed_of_meetClosed
#print axioms DualTree.MeetGeometry.meetClosed_of_coneMeetClosed
#print axioms DualTree.MeetGeometry.coneMeetClosed_iff_meetClosed
#print axioms DualTree.MeetGeometry.unique_frontier_of_boundary_of_meetClosed

#print axioms DualTree.SignatureMarker.boundaryMarker_has_leaf
#print axioms DualTree.SignatureMarker.boundaryMarker_has_support_descendant
#print axioms DualTree.SignatureMarker.coneMarker_has_support_descendant

#print axioms DualTree.DirectionalSupport.mem_allFin
#print axioms DualTree.DirectionalSupport.prefix_of_isPrefixOf_true
#print axioms DualTree.DirectionalSupport.descendant_of_uniqueBranch
#print axioms DualTree.DirectionalSupport.directional_descendants_of_fullBefore
#print axioms DualTree.DirectionalSupport.coneMarker_has_descendant_of_fullBefore

#print axioms DualTree.SkewLevelOrder.condIIIB_of_skew
#print axioms DualTree.SkewLevelOrder.length_lt_of_height_lt
#print axioms DualTree.SkewLevelOrder.paperAux_of_height_lt
#print axioms DualTree.SkewLevelOrder.forwardAux_of_height_lt
#print axioms DualTree.SkewLevelOrder.coneMarker_has_descendant_of_height_lt
