import DualTree.MixedProduct

/-!
# The c-good invariant of Definition 11

For a D2/bullet coordinate the color on a good combinatorial subspace is
allowed to remember only the marked node t_i and the letter w_i(t_i) seen
there.  All D0 and D1 data, and the rest of every word, are canonized away.

This file states Definition 11 exactly and packages its determining data as a
single bullet record.
-/

namespace DualTree.MixedProduct

/-- The data retained by Definition 11 at the D2 coordinates. -/
def bulletRecord
    {b n d : Nat} {α : Type*}
    {kind : Fin d → CoordKind}
    (x : Element b n d α kind) :
    BulletIndex kind → (BoundedNode b n × α) :=
  fun i => (x.bulletPoint i, x.words i.1 (x.bulletPoint i))

/--
Definition 11: the combinatorial subspace generated by f is c-good.
-/
def Good
    {b n d k : Nat} {α γ : Type*}
    {aux : Node b → Node b → Bool}
    {kind : Fin d → CoordKind}
    (c : Element b n d α kind → γ)
    (f : VariableWord b n d k α aux kind) : Prop :=
  ∀ ⦃x y : Element b n d α kind⦄,
    x ∈ f.span →
    y ∈ f.span →
    (∀ i : BulletIndex kind, x.bulletPoint i = y.bulletPoint i) →
    (∀ i : BulletIndex kind,
      x.words i.1 (x.bulletPoint i) =
        y.words i.1 (y.bulletPoint i)) →
    c x = c y

/--
Equivalent canonical form: on the span, the color factors through the bullet
record.
-/
theorem good_iff_same_bulletRecord
    {b n d k : Nat} {α γ : Type*}
    {aux : Node b → Node b → Bool}
    {kind : Fin d → CoordKind}
    (c : Element b n d α kind → γ)
    (f : VariableWord b n d k α aux kind) :
    Good c f ↔
      ∀ ⦃x y : Element b n d α kind⦄,
        x ∈ f.span →
        y ∈ f.span →
        bulletRecord x = bulletRecord y →
        c x = c y := by
  constructor
  · intro hgood x y hx hy hrec
    apply hgood hx hy
    · intro i
      exact congrArg Prod.fst (congrFun hrec i)
    · intro i
      exact congrArg Prod.snd (congrFun hrec i)
  · intro hrecord x y hx hy ht hv
    apply hrecord hx hy
    funext i
    apply Prod.ext
    · exact ht i
    · exact hv i

theorem color_eq_of_good_of_same_record
    {b n d k : Nat} {α γ : Type*}
    {aux : Node b → Node b → Bool}
    {kind : Fin d → CoordKind}
    {c : Element b n d α kind → γ}
    {f : VariableWord b n d k α aux kind}
    (hgood : Good c f)
    {x y : Element b n d α kind}
    (hx : x ∈ f.span) (hy : y ∈ f.span)
    (hrecord : bulletRecord x = bulletRecord y) :
    c x = c y :=
  (good_iff_same_bulletRecord c f).1 hgood hx hy hrecord

end DualTree.MixedProduct
